// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleUser   Role = "user"
	RoleSeller Role = "seller"
	RoleAdmin  Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Address struct {
	ID           uuid.UUID        `json:"id"`
	UserID       uuid.UUID        `json:"user_id"`
	AddressLine1 string           `json:"address_line1"`
	AddressLine2 pgtype.Text      `json:"address_line2"`
	City         string           `json:"city"`
	State        string           `json:"state"`
	PostalCode   string           `json:"postal_code"`
	Country      string           `json:"country"`
	Phone        string           `json:"phone"`
	IsDefault    bool             `json:"is_default"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type Category struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID            uuid.UUID        `json:"id"`
	SellerID      uuid.UUID        `json:"seller_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	Name          string           `json:"name"`
	Description   pgtype.Text      `json:"description"`
	Price         pgtype.Numeric   `json:"price"`
	StockQuantity int32            `json:"stock_quantity"`
	Images        []string         `json:"images"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Seller struct {
	ID          uuid.UUID        `json:"id"`
	OwnerID     uuid.UUID        `json:"owner_id"`
	StoreName   string           `json:"store_name"`
	Description pgtype.Text      `json:"description"`
	IsActive    bool             `json:"is_active"`
	IsVerified  bool             `json:"is_verified"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Phone        string           `json:"phone"`
	Role         Role             `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
	RefreshToken pgtype.Text      `json:"refresh_token"`
}
