// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products
(seller_id, category_id, name, description, price, stock_quantity, images)
VALUES
($1, $2, $3, $4, $5, $6, $7)
RETURNING id, seller_id, category_id, name, description, price, stock_quantity, images, created_at, updated_at
`

type CreateProductParams struct {
	SellerID      uuid.UUID      `json:"seller_id"`
	CategoryID    pgtype.UUID    `json:"category_id"`
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	Price         pgtype.Numeric `json:"price"`
	StockQuantity int32          `json:"stock_quantity"`
	Images        []string       `json:"images"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SellerID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQuantity,
		arg.Images,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, seller_id, category_id, name, description, price, stock_quantity, images, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsByCategoryId = `-- name: GetProductsByCategoryId :many
SELECT id, seller_id, category_id, name, description, price, stock_quantity, images, created_at, updated_at FROM products WHERE category_id = $1
`

func (q *Queries) GetProductsByCategoryId(ctx context.Context, categoryID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByCategoryId, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQuantity,
			&i.Images,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsBySellerId = `-- name: GetProductsBySellerId :many
SELECT id, seller_id, category_id, name, description, price, stock_quantity, images, created_at, updated_at FROM products WHERE seller_id = $1
`

func (q *Queries) GetProductsBySellerId(ctx context.Context, sellerID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsBySellerId, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQuantity,
			&i.Images,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = $2, name = $3, description = $4, images = $5
WHERE id = $1
RETURNING id, seller_id, category_id, name, description, price, stock_quantity, images, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID   `json:"id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Images      []string    `json:"images"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Images,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductPrice = `-- name: UpdateProductPrice :one
UPDATE products
SET price = $2
WHERE id = $1
RETURNING id, seller_id, category_id, name, description, price, stock_quantity, images, created_at, updated_at
`

type UpdateProductPriceParams struct {
	ID    uuid.UUID      `json:"id"`
	Price pgtype.Numeric `json:"price"`
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductPrice, arg.ID, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStockQuantity = `-- name: UpdateProductStockQuantity :one
UPDATE products
SET stock_quantity = $2
WHERE id = $1
RETURNING id, seller_id, category_id, name, description, price, stock_quantity, images, created_at, updated_at
`

type UpdateProductStockQuantityParams struct {
	ID            uuid.UUID `json:"id"`
	StockQuantity int32     `json:"stock_quantity"`
}

func (q *Queries) UpdateProductStockQuantity(ctx context.Context, arg UpdateProductStockQuantityParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStockQuantity, arg.ID, arg.StockQuantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
