// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailAndRole(ctx context.Context, arg GetUserByEmailAndRoleParams) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
