// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seller.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO sellers
(owner_id, store_name, description)
VALUES
($1, $2, $3)
RETURNING id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at
`

type CreateSellerParams struct {
	OwnerID     uuid.UUID   `json:"owner_id"`
	StoreName   string      `json:"store_name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSeller, arg.OwnerID, arg.StoreName, arg.Description)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerById = `-- name: GetSellerById :one
SELECT id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at FROM sellers WHERE id = $1
`

func (q *Queries) GetSellerById(ctx context.Context, id uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerById, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerByOwnerId = `-- name: GetSellerByOwnerId :one
SELECT id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at FROM sellers WHERE owner_id = $1
`

func (q *Queries) GetSellerByOwnerId(ctx context.Context, ownerID uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByOwnerId, ownerID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerByStoreName = `-- name: GetSellerByStoreName :one
SELECT id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at FROM sellers WHERE store_name = $1
`

func (q *Queries) GetSellerByStoreName(ctx context.Context, storeName string) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByStoreName, storeName)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSellerAsActive = `-- name: MarkSellerAsActive :one
UPDATE sellers
SET is_active = TRUE
WHERE id = $1
RETURNING id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at
`

func (q *Queries) MarkSellerAsActive(ctx context.Context, id uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, markSellerAsActive, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSellerAsInactive = `-- name: MarkSellerAsInactive :one
UPDATE sellers
SET is_active = FALSE
WHERE id = $1
RETURNING id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at
`

func (q *Queries) MarkSellerAsInactive(ctx context.Context, id uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, markSellerAsInactive, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSellerAsUnverified = `-- name: MarkSellerAsUnverified :one
UPDATE sellers
SET is_verified = FALSE
WHERE id = $1
RETURNING id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at
`

func (q *Queries) MarkSellerAsUnverified(ctx context.Context, id uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, markSellerAsUnverified, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSellerAsVerified = `-- name: MarkSellerAsVerified :one
UPDATE sellers
SET is_verified = TRUE
WHERE id = $1
RETURNING id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at
`

func (q *Queries) MarkSellerAsVerified(ctx context.Context, id uuid.UUID) (Seller, error) {
	row := q.db.QueryRow(ctx, markSellerAsVerified, id)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSeller = `-- name: UpdateSeller :one
UPDATE sellers
SET store_name = $2, description = $3
WHERE id = $1
RETURNING id, owner_id, store_name, description, is_active, is_verified, created_at, updated_at
`

type UpdateSellerParams struct {
	ID          uuid.UUID   `json:"id"`
	StoreName   string      `json:"store_name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSeller, arg.ID, arg.StoreName, arg.Description)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.StoreName,
		&i.Description,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
