// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: table.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
    user_id,
    address_line1,
    address_line2,
    city,
    state,
    postal_code,
    country,
    phone,
    is_default
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOT EXISTS (
        SELECT 1
        FROM addresses
        WHERE user_id = $1
    )
)
RETURNING id, user_id, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at, deleted_at
`

type CreateAddressParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	AddressLine1 string      `json:"address_line1"`
	AddressLine2 pgtype.Text `json:"address_line2"`
	City         string      `json:"city"`
	State        string      `json:"state"`
	PostalCode   string      `json:"postal_code"`
	Country      string      `json:"country"`
	Phone        string      `json:"phone"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddressById = `-- name: GetAddressById :one
SELECT id, user_id, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at, deleted_at FROM addresses WHERE id = $1
`

func (q *Queries) GetAddressById(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressById, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllAddressesOfUser = `-- name: GetAllAddressesOfUser :many
SELECT id, user_id, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at, deleted_at FROM addresses WHERE user_id = $1
`

func (q *Queries) GetAllAddressesOfUser(ctx context.Context, userID uuid.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAllAddressesOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE addresses
SET is_default = CASE WHEN addresses.id = $1 THEN true ELSE false END
WHERE user_id = (SELECT user_id FROM addresses WHERE addresses.id = $1)
`

func (q *Queries) SetDefaultAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultAddress, id)
	return err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET address_line1 = $2, address_line2 = $3, city = $4, state = $5, postal_code = $6, country = $7, phone = $8, is_default = $9
WHERE id = $1
RETURNING id, user_id, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at, deleted_at
`

type UpdateAddressParams struct {
	ID           uuid.UUID   `json:"id"`
	AddressLine1 string      `json:"address_line1"`
	AddressLine2 pgtype.Text `json:"address_line2"`
	City         string      `json:"city"`
	State        string      `json:"state"`
	PostalCode   string      `json:"postal_code"`
	Country      string      `json:"country"`
	Phone        string      `json:"phone"`
	IsDefault    bool        `json:"is_default"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
