app:
    name: "E-commerce"
    env: "development"
    version: "v1.0.0"

server:
    port: "8000"

pagination:
    defaultLimit: 20

jwt:
    accessTokenExpiration: 15m # 15 minutes
    refreshTokenExpiration: 168h # 7 days